/*
Create a function, that accepts an arbitrary number of arrays and returns a single array generated by alternately appending elements from the passed in arguments. 
If one of them is shorter than the others, the result should be padded with empty elements.
*/

function interleave(...array) {
    let arr = []
    let biggestLength = Math.max(...array.map(x => x.length))
    for(let i = 0; i < array.length; i++){
        for(let x = 0; x < biggestLength; x++){
            for(let z = 0; z < array.length; z++){
                arr.push(array[i + z][x] !== undefined ? array[i + z][x] : null)
            }
        }
        break
    }
    return arr
}

// tests

console.log(interleave([1, 2, 3], ["c", "d", "e"]))
console.log(interleave([1, 2, 3], [4, 5]))
console.log(interleave([1, 2, 3], [4, 5, 6], [7, 8, 9]))
console.log(interleave([]))
console.log(interleave([1, 2], [3, 4, 5]))
console.log(interleave(
    [ 'D', 'b', 4, 's', 'p' ],
  [
    'r', '5', 'a', 'i',
    'w', 1,   9,   'k'
  ],
  [ '1', 'x', 'u', 'A' ],
  [
    0,   '8', 'Z', '2',
    'c', 'd', 'H', 'G'
  ]))